namn = input("Vad heter du?")
print(namn, "är ett fint namn.")
mat = input("Vilken är din favorit maträtt?")
print(namn, mat, "är verkligen gott!")
input("Hur mycket pengar har du?")
print(namn, "du är rik.")